### ISSUE TITLE
Design Punch List

### ISSUE THREAD

**Issue by abours** [CSIS-iLab/amti_2016#42]
- [x] Search box in footer should mimic the search box on post pages: http://amti2016.staging.wpengine.com/keeping-peace-post-arbitration/

- [x] Hover/Select on top nav should be #00b29e. 

- [x] H2 color should be #023850.

- [x] H1/H3 color should be #058d79.

- [x] Remove blue border glow around search boxes once you select. 

- [x] On Maps landing page, box fill color should change to #023850 on hover and select.

- [x] On individual map pages, the button "view other AMTI maps" should be centered, and placed below/after the text. 

- [x] On the island tracker country landing pages, instead of linked text that says "Click here to explore" can we use a button that simply says "explore"? It can look like the buttons on the map pages.

- [x] Upload new favicon.

- [ ] Rework the layout of Features listing page (comp to come). 

- [x] Adjust style of Published/Category byline to 14px, all caps, PT sans narrow, same grey as paragraph text. 

- [x] Add a button "More features" to bottom of every Feature that links back to Feature listing page.

- [x] Adjust Block Quote style: make 4px larger.
